---
title: "Is an automatic or manual transmission better for MPG?"
author: "Dmytro Savich"
---
Using devices such as Jawbone Up, Nike FuelBand, and Fitbit it is now possible to collect a large amount of data about personal activity relatively inexpensively. These type of devices are part of the quantified self movement - a group of enthusiasts who take measurements about themselves regularly to improve their health, to find patterns in their behavior, or because they are tech geeks. One thing that people regularly do is quantify how much of a particular activity they do, but they rarely quantify how well they do it. In this project, your goal will be to use data from accelerometers on the belt, forearm, arm, and dumbell of 6 participants. They were asked to perform barbell lifts correctly and incorrectly in 5 different ways. More information is available from the website [here](http://groupware.les.inf.puc-rio.br/har)  




```{r}

library(doParallel)
library(caret)
library(rpart)
library(dplyr)


setwd("D:\\John Hopkins\\MachineLearning\\assingment")
data<-read.csv("pml-training.csv")
test<-read.csv("pml-testing.csv")
test<-select(test, -problem_id)
test$classe<-"A"
all_data<-rbind(data,test)




trainIn<-createDataPartition(y=data$classe, p = .75, list= FALSE)
training<-data[trainIn,]
testing<-data[-trainIn,]

##trining model excluding empty variables
data<-data[,-1]
data[data==""]<-NA
namesIn<-apply(data,2,function(x){sum(as.numeric(is.na(x)))})
trainNoNAs <- data[,namesIn==0]
trainIn<-createDataPartition(y=trainNoNAs$classe, p = .75, list= FALSE)
training<-trainNoNAs[trainIn,]
cv<-trainNoNAs[-trainIn,]

##model worked perfectly for assingment
#modFit<-train(classe~., data = training, method = "rf")


registerDoParallel(cores=2)
modFit<-train(classe~., data = training, method = "rf")
modFit$finalmodel


```

modFit$finalModel

Call:
 randomForest(x = x, y = y, mtry = param$mtry) 
               Type of random forest: classification
                     Number of trees: 500
No. of variables tried at each split: 41

        OOB estimate of  error rate: 0.05%
Confusion matrix:
     A    B    C    D    E  class.error
A 4185    0    0    0    0 0.0000000000
B    1 2846    1    0    0 0.0007022472
C    0    2 2565    0    0 0.0007791196
D    0    0    1 2410    1 0.0008291874
E    0    0    0    2 2704 0.0007390983








Random Forest 

14718 samples
   58 predictor
    5 classes: 'A', 'B', 'C', 'D', 'E' 

No pre-processing
Resampling: Bootstrapped (25 reps) 

Summary of sample sizes: 14718, 14718, 14718, 14718, 14718, 14718, ... 

Resampling results across tuning parameters:

  mtry  Accuracy   Kappa      Accuracy SD   Kappa SD    
   2    0.9875776  0.9842746  0.0021773426  0.0027512212
  41    0.9983661  0.9979323  0.0006560023  0.0008296049
  80    0.9972331  0.9964983  0.0010129622  0.0012819111

Accuracy was used to select the optimal model using  the largest value.
The final value used for the model was mtry = 41. 
> 






Confusion Matrix and Statistics

          Reference
Prediction    A    B    C    D    E
         A 1395    2    0    0    0
         B    0  947    1    0    0
         C    0    0  854    1    0
         D    0    0    0  803    0
         E    0    0    0    0  901

Overall Statistics
                                          
               Accuracy : 0.9992          
                 95% CI : (0.9979, 0.9998)
    No Information Rate : 0.2845          
    P-Value [Acc > NIR] : < 2.2e-16       
                                          
                  Kappa : 0.999           
 Mcnemar's Test P-Value : NA              

Statistics by Class:

                     Class: A Class: B Class: C Class: D Class: E
Sensitivity            1.0000   0.9979   0.9988   0.9988   1.0000
Specificity            0.9994   0.9997   0.9998   1.0000   1.0000
Pos Pred Value         0.9986   0.9989   0.9988   1.0000   1.0000
Neg Pred Value         1.0000   0.9995   0.9998   0.9998   1.0000
Prevalence             0.2845   0.1935   0.1743   0.1639   0.1837
Detection Rate         0.2845   0.1931   0.1741   0.1637   0.1837
Detection Prevalence   0.2849   0.1933   0.1743   0.1637   0.1837
Balanced Accuracy      0.9997   0.9988   0.9993   0.9994   1.0000